import mongoose from 'mongoose';
import { connectDB, disconnectDB } from '../config/db.js';
import { User } from '../models/User.js';
import { Company } from '../models/Company.js';
import { Job } from '../models/Job.js';
import { ROLES, REMOTE_TYPES, EMPLOYMENT_TYPES, JOB_STATUS } from '@jobconnect/shared';

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export async function seed50Jobs() {
  console.log('🚀 Seeding 50+ diverse, production-ready tech jobs...');
  await connectDB();

  try {
    // 1. Get or create recruiter user
    let recruiter = await User.findOne({ role: ROLES.RECRUITER });
    if (!recruiter) {
      recruiter = await User.findOne();
      if (!recruiter) {
        console.error('❌ No user found to assign as recruiter.');
        return;
      }
    }

    // 2. Define top companies
    const companiesData = [
      {
        name: 'Google India',
        slug: 'google-india',
        description: 'Global tech leader organizing the world\'s information and making it universally accessible and useful.',
        website: 'https://careers.google.com',
        industry: 'Internet & Cloud Services',
        companySize: '10,000+',
        location: 'Bangalore / Hyderabad, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Microsoft IDC',
        slug: 'microsoft-india',
        description: 'Empowering every person and organization on the planet to achieve more through Azure, Office, and AI.',
        website: 'https://careers.microsoft.com',
        industry: 'Enterprise Software & Cloud',
        companySize: '10,000+',
        location: 'Hyderabad / Bangalore, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Amazon Web Services',
        slug: 'aws-india',
        description: 'World\'s most comprehensive and broadly adopted cloud platform, offering over 200 fully featured services.',
        website: 'https://aws.amazon.com',
        industry: 'Cloud Infrastructure',
        companySize: '10,000+',
        location: 'Bangalore / Pune, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Atlassian',
        slug: 'atlassian-india',
        description: 'Makers of Jira, Confluence, Bitbucket, and Trello powering collaboration for high-performing teams.',
        website: 'https://www.atlassian.com/company/careers',
        industry: 'Collaboration Software',
        companySize: '5,000-10,000',
        location: 'Bangalore, India (Remote-First)',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Flipkart',
        slug: 'flipkart',
        description: 'India\'s homegrown e-commerce marketplace pioneering scale, supply chain tech, and digital payments.',
        website: 'https://www.flipkartcareers.com',
        industry: 'E-commerce & Logistics',
        companySize: '10,000+',
        location: 'Bangalore, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Swiggy',
        slug: 'swiggy',
        description: 'India\'s leading on-demand convenience platform connecting millions of consumers with hyperlocal services.',
        website: 'https://careers.swiggy.com',
        industry: 'Hyperlocal & Quick Commerce',
        companySize: '5,000-10,000',
        location: 'Bangalore, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Zomato & Blinkit',
        slug: 'zomato-blinkit',
        description: 'Better food for more people and instant quick-commerce deliveries across 1,000+ cities in India.',
        website: 'https://www.zomato.com/careers',
        industry: 'FoodTech & Quick Commerce',
        companySize: '5,000-10,000',
        location: 'Gurgaon (Delhi NCR), India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Cred',
        slug: 'cred-club',
        description: 'Members-only club that rewards individuals for their high trust and timely credit bill payments.',
        website: 'https://cred.club/careers',
        industry: 'FinTech & High Trust Network',
        companySize: '500-1,000',
        location: 'Bangalore, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Zerodha',
        slug: 'zerodha-tech',
        description: 'India\'s largest retail stockbroker built entirely on open-source technology, Python, Go, and Vue.',
        website: 'https://zerodha.com/careers',
        industry: 'Fintech & WealthTech',
        companySize: '1,000-2,000',
        location: 'Bangalore, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Postman',
        slug: 'postman-inc',
        description: 'The world\'s leading API platform used by over 30 million developers and 500,000 organizations.',
        website: 'https://www.postman.com/company/careers/',
        industry: 'Developer Tools & APIs',
        companySize: '1,000-2,000',
        location: 'Bangalore, India (Remote-Friendly)',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Uber India',
        slug: 'uber-india-tech',
        description: 'Engineering the mobility, freight, and safety systems powering millions of daily rides worldwide.',
        website: 'https://www.uber.com/careers',
        industry: 'Transportation & Mobility',
        companySize: '5,000-10,000',
        location: 'Hyderabad / Bangalore, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      },
      {
        name: 'PhonePe',
        slug: 'phonepe-tech',
        description: 'India\'s digital payments behemoth processing over 6 billion monthly transactions with ultra-high availability.',
        website: 'https://www.phonepe.com/careers',
        industry: 'Fintech & UPI Payments',
        companySize: '5,000-10,000',
        location: 'Bangalore / Pune, India',
        recruiterIds: [recruiter._id],
        isVerified: true,
        isActive: true,
      }
    ];

    const companyMap = new Map<string, mongoose.Types.ObjectId>();

    for (const c of companiesData) {
      let existing = await Company.findOne({ slug: c.slug });
      if (!existing) {
        existing = await Company.create(c);
      }
      companyMap.set(c.slug, existing._id as mongoose.Types.ObjectId);
    }

    const cIds = Array.from(companyMap.values());

    // 3. Define 52 distinct job roles
    const rawJobs = [
      // Frontend & Mobile
      {
        title: 'Senior Frontend Engineer (React & TypeScript)',
        companySlug: 'atlassian-india',
        skills: ['react', 'typescript', 'tailwind css', 'redux', 'jest'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 8,
        salaryMin: 2400000,
        salaryMax: 3800000,
        description: 'Architect performant, accessible UI workflows for enterprise collaboration suites. Deep expertise in React 18, Concurrent Mode, and TypeScript required.',
      },
      {
        title: 'Staff UI Systems Architect',
        companySlug: 'cred-club',
        skills: ['react', 'webgl', 'three.js', 'design systems', 'performance'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 7,
        experienceMax: 12,
        salaryMin: 4200000,
        salaryMax: 6500000,
        description: 'Design world-class, buttery smooth micro-animations, custom graphics shaders, and the foundational design system for CRED mobile & web experiences.',
      },
      {
        title: 'Lead Mobile Developer (React Native)',
        companySlug: 'swiggy',
        skills: ['react native', 'typescript', 'ios', 'android', 'redux-saga'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 5,
        experienceMax: 9,
        salaryMin: 3000000,
        salaryMax: 4800000,
        description: 'Lead the consumer mobile app driving millions of daily orders. Optimize bundle size, native bridge calls, app bootup time, and real-time tracking.',
      },
      {
        title: 'Android Platform Engineer (Kotlin & Jetpack)',
        companySlug: 'phonepe-tech',
        skills: ['kotlin', 'jetpack compose', 'coroutine', 'dagger-hilt', 'android'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 2200000,
        salaryMax: 3500000,
        description: 'Scale our UPI checkout and banking SDKs used across 500+ million devices. Focus on battery efficiency, low latency network retry, and military-grade security.',
      },
      {
        title: 'iOS Senior Software Engineer (Swift / SwiftUI)',
        companySlug: 'uber-india-tech',
        skills: ['swift', 'swiftui', 'combine', 'ribs', 'ios sdk'],
        location: 'Hyderabad, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 8,
        salaryMin: 2800000,
        salaryMax: 4500000,
        description: 'Build real-time driver dispatch and rider dispatch navigation systems. Master complex threading, background location updates, and WebSocket synchronization.',
      },
      {
        title: 'Next.js & Jamstack Developer',
        companySlug: 'postman-inc',
        skills: ['next.js', 'react', 'graphql', 'typescript', 'tailwind css'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 2,
        experienceMax: 5,
        salaryMin: 1500000,
        salaryMax: 2600000,
        description: 'Develop developer portal documentation, interactive API explorer consoles, and lightning fast server-side rendered marketing pages.',
      },

      // Backend & Distributed Systems
      {
        title: 'Principal Distributed Systems Engineer',
        companySlug: 'google-india',
        skills: ['go', 'distributed systems', 'grpc', 'spanner', 'kubernetes'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 8,
        experienceMax: 14,
        salaryMin: 5500000,
        salaryMax: 8500000,
        description: 'Design global-scale storage and routing layers handling millions of QPS. Deep understanding of Paxos/Raft consensus, vector clocks, and multi-region replication.',
      },
      {
        title: 'Senior Node.js Backend Engineer',
        companySlug: 'postman-inc',
        skills: ['node.js', 'typescript', 'postgresql', 'redis', 'docker'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 8,
        salaryMin: 2500000,
        salaryMax: 3800000,
        description: 'Build high-throughput collaboration APIs for millions of API collections. Design RESTful schemas, database indexing strategies, and automated telemetry.',
      },
      {
        title: 'Backend Systems Engineer (Golang)',
        companySlug: 'zerodha-tech',
        skills: ['go', 'postgresql', 'redis', 'websockets', 'linux'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 2,
        experienceMax: 6,
        salaryMin: 1800000,
        salaryMax: 3200000,
        description: 'Write clean, zero-allocation Go microservices handling stock market tick streams, order execution matching, and instant trade confirmation broadcasts.',
      },
      {
        title: 'High-Scale Java Backend Lead',
        companySlug: 'flipkart',
        skills: ['java', 'spring boot', 'kafka', 'cassandra', 'elasticsearch'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 6,
        experienceMax: 10,
        salaryMin: 3500000,
        salaryMax: 5200000,
        description: 'Scale our Big Billion Days inventory reservation engine. Ensure 99.999% reliability under extreme burst traffic without double-booking or inventory drift.',
      },
      {
        title: 'Python Backend Specialist (FastAPI & AsyncIO)',
        companySlug: 'zomato-blinkit',
        skills: ['python', 'fastapi', 'asyncio', 'postgresql', 'redis'],
        location: 'Gurgaon, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 2000000,
        salaryMax: 3200000,
        description: 'Develop real-time rider batching, dispatch estimation, and delivery ETA prediction APIs powering sub-10 minute quick-commerce delivery operations.',
      },
      {
        title: 'Rust Core Infrastructure Engineer',
        companySlug: 'microsoft-india',
        skills: ['rust', 'systems programming', 'linux', 'memory safety', 'networking'],
        location: 'Hyderabad, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 9,
        salaryMin: 3200000,
        salaryMax: 5000000,
        description: 'Write bare-metal, memory-safe network proxies and virtualization runtimes for Azure Cloud infrastructure.',
      },

      // Full Stack Roles
      {
        title: 'Full Stack MERN Developer (Mid-Level)',
        companySlug: 'swiggy',
        skills: ['mongodb', 'express', 'react', 'node.js', 'typescript'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 2,
        experienceMax: 5,
        salaryMin: 1600000,
        salaryMax: 2600000,
        description: 'Build end-to-end partner onboarding portals, kitchen display managers, and automated payout verification dashboards using modern MERN stack.',
      },
      {
        title: 'Lead Full Stack Architect (React + Go)',
        companySlug: 'cred-club',
        skills: ['react', 'go', 'grpc', 'kafka', 'postgresql'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 6,
        experienceMax: 11,
        salaryMin: 3800000,
        salaryMax: 5800000,
        description: 'Own full-stack architecture for high-velocity peer-to-peer payments, merchant offers, and personalized financial analytics widgets.',
      },
      {
        title: 'Full Stack Engineer - Internal Tools',
        companySlug: 'uber-india-tech',
        skills: ['react', 'node.js', 'typescript', 'graphql', 'docker'],
        location: 'Hyderabad, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 6,
        salaryMin: 2000000,
        salaryMax: 3200000,
        description: 'Develop live city operations consoles, geospatial driver heatmap visualizers, and safety compliance audit portals.',
      },
      {
        title: 'Full Stack Web3 / DApp Developer',
        companySlug: 'flipkart',
        skills: ['solidity', 'ethereum', 'web3.js', 'react', 'typescript'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 2,
        experienceMax: 6,
        salaryMin: 2200000,
        salaryMax: 3600000,
        description: 'Build decentralized loyalty points, smart contract gift vouchers, and verifiable credentials on public EVM networks.',
      },

      // AI, Machine Learning & Data Science
      {
        title: 'Senior Machine Learning Scientist (GenAI & LLMs)',
        companySlug: 'google-india',
        skills: ['python', 'pytorch', 'transformers', 'gemini', 'fine-tuning'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 9,
        salaryMin: 3600000,
        salaryMax: 6000000,
        description: 'Research and deploy state-of-the-art foundation models, agentic tool-use loops, RLHF alignment, and low-latency inference pipelines.',
      },
      {
        title: 'Computer Vision Research Engineer',
        companySlug: 'uber-india-tech',
        skills: ['computer vision', 'opencv', 'deep learning', 'pytorch', 'c++'],
        location: 'Hyderabad, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 8,
        salaryMin: 2800000,
        salaryMax: 4600000,
        description: 'Implement real-time driver helmet and seatbelt detection, mask compliance, and vehicle damage inspection models on edge devices.',
      },
      {
        title: 'Data Platform Engineer (PySpark & Airflow)',
        companySlug: 'phonepe-tech',
        skills: ['python', 'spark', 'pyspark', 'airflow', 'snowflake', 'sql'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 2200000,
        salaryMax: 3500000,
        description: 'Build enterprise petabyte-scale streaming pipelines. Extract fraud signals in sub-second latency from millions of UPI transaction streams.',
      },
      {
        title: 'Recommendation Systems Engineer',
        companySlug: 'swiggy',
        skills: ['machine learning', 'python', 'embeddings', 'ranking', 'redis'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 2600000,
        salaryMax: 4000000,
        description: 'Develop real-time dish and restaurant recommendation models personalized for weather, user dietary habits, and preparation times.',
      },
      {
        title: 'AI Applied Scientist (NLP & Speech)',
        companySlug: 'microsoft-india',
        skills: ['nlp', 'speech recognition', 'huggingface', 'python', 'pytorch'],
        location: 'Hyderabad, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 8,
        salaryMin: 3000000,
        salaryMax: 5000000,
        description: 'Train multilingual speech and text translation models supporting 22 official Indian languages for enterprise voice bots.',
      },
      {
        title: 'Senior Business Intelligence & Analytics Engineer',
        companySlug: 'zomato-blinkit',
        skills: ['sql', 'tableau', 'python', 'dbt', 'bigquery'],
        location: 'Gurgaon, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 6,
        salaryMin: 1800000,
        salaryMax: 2800000,
        description: 'Build automated attribution models, warehouse dark-store operational KPIs, and executive reporting dashboards.',
      },

      // Cloud, DevOps & Platform Engineering
      {
        title: 'Staff Kubernetes & Platform Engineer',
        companySlug: 'aws-india',
        skills: ['kubernetes', 'eks', 'terraform', 'golang', 'helm'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 6,
        experienceMax: 12,
        salaryMin: 3800000,
        salaryMax: 5800000,
        description: 'Architect developer platforms powering automated cluster lifecycle, blue-green ingress controllers, and multi-tenant isolation.',
      },
      {
        title: 'Site Reliability Engineer II (SRE)',
        companySlug: 'atlassian-india',
        skills: ['linux', 'prometheus', 'grafana', 'python', 'aws', 'incident management'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 2200000,
        salaryMax: 3400000,
        description: 'Champion error budgets, automate disaster recovery drills, tune database connection pools, and drive post-mortem blameless reviews.',
      },
      {
        title: 'Cloud Security & DevSecOps Lead',
        companySlug: 'phonepe-tech',
        skills: ['aws security', 'iam', 'vault', 'siem', 'penetration testing'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 5,
        experienceMax: 10,
        salaryMin: 3200000,
        salaryMax: 4800000,
        description: 'Fortify production cloud perimeter, manage key rotation via HashiCorp Vault, enforce zero-trust network policies, and audit PCI-DSS compliance.',
      },
      {
        title: 'CI/CD & Release Automation Engineer',
        companySlug: 'postman-inc',
        skills: ['github actions', 'docker', 'bash', 'node.js', 'release management'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 2,
        experienceMax: 5,
        salaryMin: 1500000,
        salaryMax: 2400000,
        description: 'Build blazing-fast automated build matrix pipelines cutting cross-platform desktop release times from 2 hours to 8 minutes.',
      },

      // Product Management & Design
      {
        title: 'Senior Product Manager - Consumer Growth',
        companySlug: 'cred-club',
        skills: ['product management', 'growth metrics', 'a/b testing', 'ux research'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 8,
        salaryMin: 3000000,
        salaryMax: 5000000,
        description: 'Define product roadmap for user acquisition, gamified reward loops, viral referral channels, and retention cohorts.',
      },
      {
        title: 'Principal Product Manager - Cloud Infrastructure',
        companySlug: 'aws-india',
        skills: ['product management', 'cloud services', 'api design', 'b2b saas'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 7,
        experienceMax: 13,
        salaryMin: 4500000,
        salaryMax: 7000000,
        description: 'Lead developer experience, billing granularity, and SLAs for mission-critical serverless computing services.',
      },
      {
        title: 'Lead Product Designer (UI/UX)',
        companySlug: 'swiggy',
        skills: ['figma', 'user journey mapping', 'wireframing', 'design systems'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 5,
        experienceMax: 9,
        salaryMin: 2600000,
        salaryMax: 4200000,
        description: 'Own the dining-out and food discovery design experience. Conduct in-depth field research with restaurant partners and end diners.',
      },
      {
        title: 'Design Systems & Motion Specialist',
        companySlug: 'atlassian-india',
        skills: ['figma', 'design systems', 'motion design', 'framer', 'css'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 2000000,
        salaryMax: 3200000,
        description: 'Build and maintain our global token-based component design system used by over 800 engineers across 15 products.',
      },

      // QA & SDET (Software Development Engineer in Test)
      {
        title: 'Staff SDET - Performance & Chaos Testing',
        companySlug: 'flipkart',
        skills: ['jmeter', 'gatling', 'chaos engineering', 'java', 'distributed systems'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 5,
        experienceMax: 10,
        salaryMin: 2800000,
        salaryMax: 4400000,
        description: 'Simulate million-user flash sales, inject simulated network degradation, and verify failover behaviors across multi-datacenter clusters.',
      },
      {
        title: 'Senior Automation QA Engineer (Playwright & TypeScript)',
        companySlug: 'postman-inc',
        skills: ['playwright', 'typescript', 'api testing', 'ci/cd', 'selenium'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 1800000,
        salaryMax: 2800000,
        description: 'Design robust, parallelized end-to-end test suites covering complex real-time WebSocket workspaces and collaborative canvas flows.',
      },

      // Security & Infrastructure
      {
        title: 'Application Security Engineer (AppSec)',
        companySlug: 'zerodha-tech',
        skills: ['owasp', 'appsec', 'code audit', 'penetration testing', 'burp suite'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 2400000,
        salaryMax: 3800000,
        description: 'Perform source code security reviews, manage public bug bounty programs, and build automated static code analysis gates in CI/CD.',
      },
      {
        title: 'Database Administrator (PostgreSQL & CockroachDB)',
        companySlug: 'phonepe-tech',
        skills: ['postgresql', 'cockroachdb', 'query tuning', 'replication', 'wal'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 9,
        salaryMin: 2600000,
        salaryMax: 4000000,
        description: 'Manage 500+ database instances. Optimize execution plans, index usage, connection pooling, and online schema migrations with zero downtime.',
      },

      // Junior / Fresher / Internship Roles
      {
        title: 'Associate Software Engineer (Graduate 2026 Batch)',
        companySlug: 'microsoft-india',
        skills: ['c++', 'data structures', 'algorithms', 'python', 'git'],
        location: 'Hyderabad, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 0,
        experienceMax: 2,
        salaryMin: 1400000,
        salaryMax: 2200000,
        description: 'Launch your software engineering career working on foundational cloud services, enterprise developer tools, and cutting-edge generative AI.',
      },
      {
        title: 'Frontend Engineering Intern (Summer 2026)',
        companySlug: 'swiggy',
        skills: ['javascript', 'react', 'css', 'html', 'git'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.INTERNSHIP,
        experienceMin: 0,
        experienceMax: 1,
        salaryMin: 600000,
        salaryMax: 900000,
        description: 'Hands-on 6-month software internship working with senior mentors on customer discovery widgets, food ordering animations, and web vitals.',
      },
      {
        title: 'Backend Engineering Intern (Node.js & Go)',
        companySlug: 'zomato-blinkit',
        skills: ['node.js', 'go', 'mongodb', 'rest apis', 'docker'],
        location: 'Gurgaon, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.INTERNSHIP,
        experienceMin: 0,
        experienceMax: 1,
        salaryMin: 700000,
        salaryMax: 1000000,
        description: 'Work directly on live microservices, write unit and integration test suites, and learn real-world distributed caching techniques.',
      },
      {
        title: 'Data Science Intern',
        companySlug: 'flipkart',
        skills: ['python', 'pandas', 'scikit-learn', 'sql', 'statistics'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.INTERNSHIP,
        experienceMin: 0,
        experienceMax: 1,
        salaryMin: 600000,
        salaryMax: 850000,
        description: 'Analyze user search trends, evaluate A/B test campaign significance, and train baseline regression models for price optimization.',
      },

      // Additional Specialized Engineering Roles
      {
        title: 'Lead Observability Engineer (OpenTelemetry & Kafka)',
        companySlug: 'uber-india-tech',
        skills: ['opentelemetry', 'kafka', 'jaeger', 'golang', 'clickhouse'],
        location: 'Hyderabad, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 5,
        experienceMax: 9,
        salaryMin: 3200000,
        salaryMax: 4800000,
        description: 'Scale distributed tracing and log collection pipelines ingesting over 50 terabytes of telemetry data daily.',
      },
      {
        title: 'Senior FinTech Infrastructure Specialist',
        companySlug: 'cred-club',
        skills: ['banking integrations', 'npc', 'iso8583', 'go', 'security'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 8,
        salaryMin: 3000000,
        salaryMax: 4600000,
        description: 'Build direct bank host-to-host integrations, instant settlement reconciliation ledgers, and credit card statement parsers.',
      },
      {
        title: 'Solutions Architect - Enterprise Cloud',
        companySlug: 'aws-india',
        skills: ['cloud architecture', 'aws', 'migration', 'security', 'consulting'],
        location: 'Mumbai, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 6,
        experienceMax: 11,
        salaryMin: 3400000,
        salaryMax: 5200000,
        description: 'Advise Fortune 500 enterprises on multi-account AWS architectures, zero-downtime database migrations, and cost governance.',
      },
      {
        title: 'Search & Relevance Engineer (Elasticsearch)',
        companySlug: 'flipkart',
        skills: ['elasticsearch', 'lucene', 'python', 'nlp', 'ranking'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 4,
        experienceMax: 8,
        salaryMin: 2800000,
        salaryMax: 4400000,
        description: 'Optimize search relevance algorithms, typos tolerance, autocomplete suggestions, and category ranking across 200M+ catalog items.',
      },
      {
        title: 'Site Reliability Architect',
        companySlug: 'google-india',
        skills: ['sre', 'distributed systems', 'linux', 'go', 'networking'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 7,
        experienceMax: 13,
        salaryMin: 4800000,
        salaryMax: 7500000,
        description: 'Ensure 99.999% availability for planetary-scale services, drive automation to eliminate toil, and maintain global network backbones.',
      },
      {
        title: 'Technical Writer & Developer Relations Engineer',
        companySlug: 'postman-inc',
        skills: ['technical writing', 'apis', 'javascript', 'markdown', 'community'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 2,
        experienceMax: 6,
        salaryMin: 1600000,
        salaryMax: 2600000,
        description: 'Author tutorials, code samples, SDK documentation, and sample API collections empowering developers worldwide.',
      },
      {
        title: 'Lead Cryptography & Key Management Engineer',
        companySlug: 'phonepe-tech',
        skills: ['cryptography', 'hsm', 'pki', 'tls', 'java'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 5,
        experienceMax: 10,
        salaryMin: 3400000,
        salaryMax: 5000000,
        description: 'Design Hardware Security Module (HSM) integrations, tokenization vaults, and end-to-end payload encryption for banking protocols.',
      },
      {
        title: 'Senior Contract React Native Specialist (6 Months)',
        companySlug: 'swiggy',
        skills: ['react native', 'typescript', 'mobile optimization'],
        location: 'Remote, India',
        remoteType: REMOTE_TYPES.REMOTE,
        employmentType: EMPLOYMENT_TYPES.CONTRACT,
        experienceMin: 4,
        experienceMax: 8,
        salaryMin: 2000000,
        salaryMax: 3000000,
        description: '6-month high-impact contract to revamp the partner driver delivery mobile app interface and optimize GPS battery consumption.',
      },
      {
        title: 'DevOps & Infrastructure Consultant (Contract)',
        companySlug: 'zerodha-tech',
        skills: ['linux', 'ansible', 'freebsd', 'networking', 'security'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.CONTRACT,
        experienceMin: 5,
        experienceMax: 10,
        salaryMin: 2500000,
        salaryMax: 3800000,
        description: 'Consult on custom kernel optimizations, zero-copy packet processing, and low-latency network interface tuning.',
      },
      {
        title: 'Senior Growth & Product Analyst',
        companySlug: 'zomato-blinkit',
        skills: ['sql', 'r', 'python', 'experimentation', 'cohort analysis'],
        location: 'Gurgaon, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 6,
        salaryMin: 1800000,
        salaryMax: 2700000,
        description: 'Model customer retention elasticity, evaluate subscription plans (Zomato Gold), and optimize cart checkout funnels.',
      },
      {
        title: 'Frontend Engineer (Angular & Micro-Frontends)',
        companySlug: 'microsoft-india',
        skills: ['angular', 'typescript', 'module federation', 'rxjs', 'karma'],
        location: 'Hyderabad, India',
        remoteType: REMOTE_TYPES.HYBRID,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 3,
        experienceMax: 7,
        salaryMin: 2200000,
        salaryMax: 3400000,
        description: 'Build enterprise administrative micro-frontends with high test coverage, strict type contracts, and reactive RxJS state stores.',
      },
      {
        title: 'Hardware & IoT Integration Engineer',
        companySlug: 'swiggy',
        skills: ['embedded systems', 'c', 'iot', 'mqtt', 'bluetooth le'],
        location: 'Bangalore, India',
        remoteType: REMOTE_TYPES.ONSITE,
        employmentType: EMPLOYMENT_TYPES.FULL_TIME,
        experienceMin: 2,
        experienceMax: 6,
        salaryMin: 1700000,
        salaryMax: 2800000,
        description: 'Develop firmware and cloud connectivity for restaurant POS order printers, temperature sensors, and smart locker pickup stations.',
      }
    ];

    let createdCount = 0;
    const now = Date.now();

    for (let i = 0; i < rawJobs.length; i++) {
      const item = rawJobs[i];
      const companyId = companyMap.get(item.companySlug) || cIds[i % cIds.length];
      const uniqueSlug = `${slugify(item.title)}-${Date.now().toString(36)}-${i}`;

      await Job.create({
        title: item.title,
        slug: uniqueSlug,
        description: item.description,
        companyId: companyId,
        recruiterId: recruiter._id,
        skills: item.skills,
        location: item.location,
        remoteType: item.remoteType,
        employmentType: item.employmentType,
        experienceMin: item.experienceMin,
        experienceMax: item.experienceMax,
        salaryMin: item.salaryMin,
        salaryMax: item.salaryMax,
        currency: 'INR',
        status: JOB_STATUS.PUBLISHED,
        applicationDeadline: new Date(now + (20 + (i % 40)) * 24 * 60 * 60 * 1000),
        viewsCount: Math.floor(Math.random() * 250) + 10,
        applicantsCount: 0,
      });

      createdCount++;
    }

    const totalJobs = await Job.countDocuments();
    console.log(`🎉 Successfully created ${createdCount} new jobs! Total jobs in database: ${totalJobs}`);
  } catch (error) {
    console.error('❌ Failed to seed 50 jobs:', error);
  }
}

// Standalone execution
if (process.argv[1]?.endsWith('seed50Jobs.ts') || process.argv[1]?.endsWith('seed50Jobs.js')) {
  seed50Jobs().then(async () => {
    await disconnectDB();
    process.exit(0);
  });
}
