import { IAIProvider, AICompletionOptions } from '../interfaces/aiProvider.interface.js';

export class DeterministicAIProvider implements IAIProvider {
  readonly providerName = 'deterministic-offline-adapter';

  async generateText(prompt: string, _options?: AICompletionOptions): Promise<string> {
    // 1. Detect if prompt is Job Description Generator
    if (prompt.includes('Role Title:') && prompt.includes('Raw Recruiter Notes:')) {
      const titleMatch = prompt.match(/Role Title: (.*?)\n/);
      const title = titleMatch ? titleMatch[1] : 'Software Engineer';
      return JSON.stringify({
        title,
        overview: `We are seeking a talented ${title} to join our engineering team. You will build high-impact, scalable web applications and collaborate directly with cross-functional product teams.`,
        responsibilities: [
          'Design and maintain robust, high-performance web applications and backend APIs.',
          'Collaborate with product designers and frontend engineers to ship intuitive user experiences.',
          'Conduct code reviews, optimize database queries, and ensure adherence to security standards.',
          'Troubleshoot production incidents and optimize system latency and uptime.',
        ],
        requirements: [
          'Solid understanding of modern JavaScript, TypeScript, and modern web frameworks.',
          'Experience building and consuming RESTful and real-time APIs.',
          'Familiarity with relational and NoSQL databases such as PostgreSQL or MongoDB.',
          'Commitment to writing clean, maintainable, and well-tested code.',
        ],
        preferredSkills: [
          'Familiarity with Redis caching and distributed systems.',
          'Experience with Docker, CI/CD pipelines, and cloud deployments.',
        ],
        suggestedInterviewQuestions: [
          'Explain how you would design an authentication system with refresh token rotation.',
          'Describe a situation where you diagnosed and fixed a database query bottleneck.',
        ],
      });
    }

    // 2. Detect if prompt is Job Summary
    if (prompt.includes('UNTRUSTED JOB DESCRIPTION START')) {
      return JSON.stringify({
        roleOverview:
          'This position involves designing and maintaining scalable software services, delivering key product features, and working alongside a collaborative engineering team.',
        coreResponsibilities: [
          'Develop and optimize core application features.',
          'Participate in architecture reviews and sprint planning.',
          'Ensure adherence to security best practices and high test coverage.',
        ],
        mustHaveSkills: ['TypeScript', 'Node.js', 'React', 'Database Design'],
        experienceExpectations: 'Mid-to-Senior level engineering experience (2-5+ years).',
        salaryAndWorkMode: 'Competitive market salary with remote/hybrid flexibility as posted.',
        missingInformation: 'Specific company benefits and travel requirements were not detailed in the posting.',
      });
    }

    // 3. Detect if prompt is Candidate-Job Match
    if (prompt.includes('Candidate Background:')) {
      return JSON.stringify({
        overallMatchGrade: 'Strong Match',
        technicalSkillsMatch: {
          matchingSkills: ['TypeScript', 'React', 'Node.js', 'MongoDB'],
          missingOrRecommendedSkills: ['Redis', 'Docker', 'System Design'],
        },
        strengthsAnalysis:
          'Your profile demonstrates strong alignment with the core tech stack required for this position. Your hands-on experience matches the primary responsibilities.',
        preparationTips: [
          'Highlight concrete achievements in your resume where you scaled backend APIs or optimized queries.',
          'Review caching strategies and rate limiting patterns before the technical interview.',
        ],
        disclaimer: 'AI recommendations are for assistance only. Recruiters make final hiring decisions.',
      });
    }

    // 4. Default interactive assistant fallback
    return `### JobConnect Career Assistant Guidance

Thank you for your question! Here is targeted guidance based on your profile and current tech trends:

1. **Profile Optimization**: Ensure your top technical skills are highlighted in both your bio and headline.
2. **Project Experience**: Focus on measurable outcomes (e.g. "reduced latency by 40%", "implemented secure authentication").
3. **Continuous Learning**: Gaining familiarity with caching (Redis) and containerization (Docker) will make your profile stand out to recruiters on JobConnect.

*Note: This response is generated by JobConnect's AI Career Assistant to support your career journey.*`;
  }
}
