// Section 6A Strict Validation Constants & Patterns

export const FIRST_NAME_REGEX = /^[A-Z][a-zA-Z]+$/;
export const LAST_NAME_REGEX = /^[a-zA-Z]+(?: [a-zA-Z]+)*$/;
export const OTP_REGEX = /^[0-9]{6}$/;

// Password rules: 6-50 chars, letter, number, special character
export const PASSWORD_REGEX =
  /^(?=.{6,50}$)(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~`]).*$/;

export const VALIDATION_LIMITS = {
  FIRST_NAME_MIN: 2,
  FIRST_NAME_MAX: 50,
  LAST_NAME_MIN: 2,
  LAST_NAME_MAX: 50,
  EMAIL_MIN: 6,
  EMAIL_MAX: 254,
  PASSWORD_MIN: 6,
  PASSWORD_MAX: 50,
  MIN_AGE_YEARS: 13,
  MAX_AGE_YEARS: 120,
  OTP_LENGTH: 6,
  OTP_TTL_SECONDS: 300, // 5 minutes
  OTP_COOLDOWN_SECONDS: 60, // 60s resend cooldown
  OTP_MAX_ATTEMPTS: 5,
  MAX_UPLOAD_SIZE_BYTES: 5 * 1024 * 1024, // 5MB for resumes
  MAX_IMAGE_SIZE_BYTES: 2 * 1024 * 1024, // 2MB for logos
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_MAX_ATTEMPTS_EXCEEDED: 'OTP_MAX_ATTEMPTS_EXCEEDED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_PENDING_VERIFICATION: 'ACCOUNT_PENDING_VERIFICATION',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_DATE_OF_BIRTH: 'INVALID_DATE_OF_BIRTH',
  UNDERAGE_ACCOUNT: 'UNDERAGE_ACCOUNT',
  INVALID_QUALIFICATION: 'INVALID_QUALIFICATION',
  INVALID_GENDER: 'INVALID_GENDER',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  APPLICATION_DUPLICATE: 'APPLICATION_DUPLICATE',
  APPLICATION_CLOSED: 'APPLICATION_CLOSED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
